server:
  port: 8080
  shutdown: graceful


spring:
  config:
    import:
      - "optional:file:.env[.properties]"
  application:
    name: omnibox-search
  autoconfigure:
      exclude:
        - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:omnibox}
    username: ${DB_USER:omnibox}
    password: ${DB_PASSWORD:omnibox}
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      connection-timeout: 500
      validation-timeout: 250
      connection-init-sql: "SET TIME ZONE 'UTC'"   # UTC for each new connection
  graphql:
    graphiql:
      enabled: true
    schema:
      locations: classpath:graphql/
      printer:
        enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      slo:
        http.server.requests: 100ms,200ms,400ms

logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN
    org.springframework.graphql: DEBUG
    com.github.dimitryivaniuta.gateway.search: INFO

