server:
  port: ${OMNIBOX_SERVER_PORT:8080}
  shutdown: graceful

spring:
  config:
    import:
      - "optional:file:.env[.properties]"
  application:
    name: omnibox-search
  autoconfigure:
      exclude:
        - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  datasource:
    url: jdbc:postgresql://${READ_DB_HOST:localhost}:${READ_DB_PORT:5434}/${READ_DB_NAME:omnibox}?currentSchema=public&sslmode=disable
    username: ${READ_DB_USER:omnibox}
    password: ${READ_DB_PASSWORD:omnibox}
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      connection-timeout: 500
      validation-timeout: 250
      connection-init-sql: "SET TIME ZONE 'UTC'"   # UTC for each new connection
  graphql:
    graphiql:
      enabled: true
    schema:
      locations: classpath:graphql/
      printer:
        enabled: false
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      slo:
        http.server.requests: 100ms,200ms,400ms

logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN
    org.springframework.graphql: DEBUG
    com.github.dimitryivaniuta.gateway.search: INFO

